dataset:
  sample_rate: 8000
  n_feats: 81
  specaug_rate: 0.5
  specaug_policy: 3
  time_mask: 70
  freq_mask: 15
  log_ex: False

hyper_parameters:
  num_classes: 29
  n_feats: 81
  dropout: 0.1
  hidden_size: 1024
  num_layers: 1

lr: 0.0001